### ISSUE TITLE
Ubuntu 20.04 issue after compiling

### ISSUE THREAD

**Issue by pbaveja** [chihuahua/beautiful-audio-editor#3]
Trying to compile after cloning on Ubuntu 20.04. The error thrown is:
```
Uncaught TypeError: a.attachEvent is not a function
    at Ic (c.js:33)
```

The uncompiled.html works as expected. And this also works on Ubuntu 18.04 as expected.

Java 8 installed. And running `do.py` with python2.7

It points to an OS and Java compatibility issue. Any help would be appreciated.

**Comment by KCGD** [comment]
same issue on mint 20.2 python2.7
